version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies from requirements.txt...
      - python -m pip install --upgrade pip
      - pip install -r lambda_code/requirements.txt -t ./package

  pre_build:
    commands:
      - echo Copying Lambda function code into the package directory...
      - cp lambda_code/lambda_function.py ./package/

  build:
    commands:
      - echo Building the Lambda deployment package...
      - mkdir -p dist
      - cd package
      - zip -r ../dist/lambda_function.zip ./*
      - cd ..

artifacts:
  files:
    - dist/lambda_function.zip
